- block:
  - name: Add udev rules
    template:
      src:   "{{ inventory_dir }}/files/udev/{{ item.name }}"
      dest:  "/etc/udev/rules.d/{{ item.name }}"
    notify: Reload udev rules
    when: item.state is not defined or item.state == "present"
    loop: "{{ udev_rules }}"

  - name: Remove udev rules
    file:
      path:  "/etc/udev/rules.d/{{ item.name }}"
      state: absent
    notify: Reload udev rules
    when: item.state is defined and item.state == "absent"
    loop: "{{ udev_rules }}"

  tags: udev
